FROM python:3.8-slim

WORKDIR /usr/src/app


COPY requirements.txt /usr/src/app/
RUN pip install -r /usr/src/app/requirements.txt


COPY exporter.py /usr/src/app/exporter.py
COPY regions.py /usr/src/app/regions.py
COPY carbon_emissions.py /usr/src/app/carbon_emissions.py
COPY container_stats.py /usr/src/app/container_stats.py

EXPOSE 9877

ENTRYPOINT ["python", "/usr/src/app/exporter.py"]