{
 "title": "Carbon",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(carbon_consumption,region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Carbon Consumed (gCo2Eq)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum_over_time(carbon_consumption{region=~\"$region\"}[24h])/60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Carbon Consumed By Region",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (region) (sum_over_time(carbon_consumption[24h])/60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Carbon Consumed By Time (hour)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum by(time) (sum_over_time(carbon_consumption_time{region=~\"$region\"}[24h])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Carbon Consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "carbon_consumption{region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}