# TODO make it work
# Currently doing (in this dir)
# docker run -it -v /var/run/docker.sock:/var/run/docker.sock --mount src=`pwd`,target=/go,type=bind golang bash
# And then cd carbon-monitor/example and go run main.go
# Will be needed with the prometheus-exporter mode

FROM golang

WORKDIR /go


COPY carbon-monitor /go

ENTRYPOINT ["go", "run", "carbon-monitor/*.go"]